const Route = require('@ioc:Adonis/Core/Route')
Route.get('/', 'HomeController.index')
Route.get('/index.html', 'HomeController.index')
Route.get('/packages.html', 'HomeController.packages')
Route.get('/whatyouget.html', 'HomeController.whatyouget')
Route.get('/lokasinya.html', 'HomeController.lokasinya')
Route.get('/contact.html', 'HomeController.contact')
Route.get('/products', 'ProductController.index')
Route.get('/seller', 'SellerController.index')
Route.post('/seller/add', 'SellerController.add')
Route.post('/wishlist/add', 'TransactionController.add')
Route.post('/wishlist/remove', 'TransactionController.remove')
Route.post('/contact/send', 'ContactController.send')
